### PR TITLE
Expand on security technologies in use

### PR DESCRIPTION
**Pull request by linuxwolf**
A start on expanding the details of what cryptographic tech is in use.

_started from [Hacker News](https://news.ycombinator.com/item?id=17500804)_

### CODE REVIEW

**Comment by linuxwolf** [comment]
@changecourse @devinreams et al, let me know what you think, and if this is a decent place to expand at.

**Comment by changecourse** [comment]
Looks good to me, @linuxwolf! Thanks!

**Comment by linuxwolf** [comment]
Further, would it be appropriate to link to here from other places, including our Test Pilot page?

**Comment by changecourse** [comment]
@devinreams is there anything holding this back from being merged into our FAQ?

**Pull request merged**
